### ISSUE TITLE
Recall for detected change(class 1) is very low 

### ISSUE THREAD

**Issue by KaviyaSubramanian706** [AndreaCodegoni/Tiny_model_4_CD#12]
Hi,
After executing the the code with WHU-CD dataset with pretrained model,these are the results of the test
{'acc': 0.9484738175586964, 'miou': 0.522093921610696, 'mf1': 0.5742922406664711, 'iou_0': 0.9481903331958307, 'iou_1': 0.0959975100255613, 'F1_0': 0.9734062005987101, 'F1_1': 0.17517828073423214, 'precision_0': 0.9649982845855988, 'precision_1': 0.24004840719627082, 'recall_0': 0.9819620400564614, 'recall_1': 0.13790991201484162}

The recall for change detection seems very low at 0.13,is this the expected value,should something be altered?

**Comment by AndreaCodegoni** [comment]
Can I ask you to run the run and evaluation on the LEVIR-CD dataset? I've also noticed that in the PR you have raised you have setted
```python
model.load_state_dict(torch.load(modelpath),strict=False)
```
strict=False must be avoided because no error is returned if the weights do not match the model and you don't know if you are actually loading the weights. I think this may be your problem. Why did you set it to False? Couldn't load the model?

**Comment by KaviyaSubramanian706** [comment]
Yeah ,this was the error I faced while loading the model

 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ChangeClassifier:
	Missing key(s) in state_dict: "_mixing_mask.2._convmix.0.weight", "_mixing_mask.2._convmix.0.bias", "_mixing_mask.2._convmix.1.weight". 
	Unexpected key(s) in state_dict: "_mixing_mask.2._mixing._convmix.0.weight", "_mixing_mask.2._mixing._convmix.0.bias", "_mixing_mask.2._mixing._convmix.1.weight".

**Comment by AndreaCodegoni** [comment]
Ok. When you load the model using strict=False some parameters are random parameters and hence the model performs bad. Have you altered something in the model creation?

**Comment by kkkkkkb** [comment]
> Yeah ,this was the error I faced while loading the model
> 
> raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for ChangeClassifier: Missing key(s) in state_dict: "_mixing_mask.2._convmix.0.weight", "_mixing_mask.2._convmix.0.bias", "_mixing_mask.2._convmix.1.weight". Unexpected key(s) in state_dict: "_mixing_mask.2._mixing._convmix.0.weight", "_mixing_mask.2._mixing._convmix.0.bias", "_mixing_mask.2._mixing._convmix.1.weight".

I also met the same problem

**Comment by AndreaCodegoni** [comment]
Does it happens only with the checkpoint for the WHU dataset?

Probably I've uploaded a checkpoint after o before a refactoring. My bad.
As a quick fix, you can try to change the keys in the state dict accordingly to the error. 
Hope this work.

Let me know.
