### ISSUE TITLE
How to evaluate the model on a single image pair?

### ISSUE THREAD

**Issue by arianaa30** [AndreaCodegoni/Tiny_model_4_CD#13]
Thank you for the repo. I just want to run the pre-trained models on a **single** pair of images, say i1 and i2 and get the changes. How can I do that?

Currently this command evaluates the whole directory in the dataset.
`python3 test_ondata.py --modelpath pretrained_models/levir_best.pth`

**Comment by AndreaCodegoni** [comment]
Hello,

have you tried to replicate the folder structure described in the dataset file putting i1 in the subfolder A and i2 in the subfolder B and simply using this pair in the test.txt file?
This seems to me the quick and dirty way to evaluate two or more images with a pertained model.

You can also follow the same scheme with the same functions in dataset.py and preprocess the two images and then feed the couple in the model following the steps in test_ondata.

Let me know if you need more support.

**Comment by arianaa30** [comment]
I run this command with the default Levir test directory. But not sure why it shows this...looks like training?!

```
Number of model parameters 285128

  0%|                                                                                          | 0/2048 [00:00<?, ?it/s]  0%|
  
```
  my command:
  
`  python3 test_ondata.py --modelpath pretrained_models/levir_best.pth`

**Comment by AndreaCodegoni** [comment]
No, it looks like testing. You have to make another directory with the same structure of the Levir and put there the images you want to process. 

Then you have to to run 
```bash
python3 test_ondata.py --datapath PATH_TO_YOUR_FOLDER --modelpath pretrained_models/levir_best.pth
```
