### ISSUE TITLE
Indoor Change Detections?

### ISSUE THREAD

**Issue by arianaa30** [AndreaCodegoni/Tiny_model_4_CD#14]
While Tiny_CD is designed for remote sensing cases, a question that I have is does it work for indoor change detection?
For instance, I want to detect the changes between these two images (door opened). Does it work for such cases?

![d1](https://github.com/wgcban/ChangeFormer/assets/5509837/9f9783b9-3497-40d2-bb0b-6a86ba78d7a8)
![d2](https://github.com/wgcban/ChangeFormer/assets/5509837/eaf8acde-7198-4a11-b3a1-22edd4262537)

**Comment by AndreaCodegoni** [comment]
Well, the indoor data seems to be a little bit different from the source domain of the aerial images. You can try to evaluate a pertained model and if the results are not satisfactory you can try to fine-tune the model on your indoor dataset.
