### ISSUE TITLE
Hello, the wget and dataset download link you provided may not work, could you please update it

### ISSUE THREAD

**Issue by HZWXW371** [AndreaCodegoni/Tiny_model_4_CD#19]

**Comment by AndreaCodegoni** [comment]
Hello,

could you please try to download the preprocessed dataset from the following [link](https://drive.google.com/drive/folders/1uTExi7JbiSwXXqPdeJp2GCE7B-0QI6xh?usp=sharing).

If it works I'll update the Readme. Please let me know.

**Comment by HZWXW371** [comment]
Thank you very much for your help
