### ISSUE TITLE
Hi, are you interested in participating in the Open-CD TRP program?

### ISSUE THREAD

**Issue by likyoo** [AndreaCodegoni/Tiny_model_4_CD#23]
https://github.com/likyoo/open-cd/tree/main/projects/open-cd_technical_report

**Comment by AndreaCodegoni** [comment]
Hello! I'm following your project and I've seen that you have already integrated TinyCD. Do you need a short description of the proposed method?

**Comment by likyoo** [comment]
That's right! 😄

**Comment by likyoo** [comment]
Also, could you provide your full name, affiliation and email address to me and we will include you as one of the authors of the report. You can send it to me via email (likyoo@sdust.edu.cn). Thanks!!!

**Comment by AndreaCodegoni** [comment]
Done. Check you email :)
