### ISSUE TITLE
SyntaxError: not a PNG file

### ISSUE THREAD

**Issue by vaelaogudong** [AndreaCodegoni/Tiny_model_4_CD#7]
Hello, I made the following mistakes while training the model:

lib\site-packages\PIL\PngImagePlugin.py", line 712, in _open
    raise SyntaxError("not a PNG file")
SyntaxError: not a PNG file

There should be no problem with the data. What is the solution?

**Comment by AndreaCodegoni** [comment]
Hello,

From the error you report, it seems to me that it is an error related to the reading of the png image, not of the dataloader. If you try to use imread function of matplotlib, in a python file or in a notebook it gives you the same error?
If yes, could you post your script where you use imread and the related error?
Have you tried to see if the argument being passed to imread in the dataloader is actually the path to the PNG images?

**Comment by vaelaogudong** [comment]
Thank you for your reply. My problem has been solved. The reason for the error is that although the picture suffix name is png, the actual format is tif.

**Comment by AndreaCodegoni** [comment]
I'm glad you fixed it. I'm closing the issue, for any other problems feel free to open new ones. Have fun.
